FROM node:24

# Set the timezone to Asia/Seoul
ENV TZ=Asia/Seoul

WORKDIR /app

COPY ./backend/package*.json ./

RUN npm install
COPY ./backend .

ENV GENERATE_SOURCEMAP=false
ENV NODE_OPTIONS=--max-old-space-size=4096
ENV NODE_ENV=production
RUN npm run build

CMD ["npm", "run", "start:prod"]