/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedBucketCreateRouteImport } from './routes/_authenticated/bucket/create'
import { Route as AuthenticatedBucketBucketIdRouteImport } from './routes/_authenticated/bucket/$bucketId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBucketCreateRoute =
  AuthenticatedBucketCreateRouteImport.update({
    id: '/bucket/create',
    path: '/bucket/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBucketBucketIdRoute =
  AuthenticatedBucketBucketIdRouteImport.update({
    id: '/bucket/$bucketId',
    path: '/bucket/$bucketId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/bucket/$bucketId': typeof AuthenticatedBucketBucketIdRoute
  '/bucket/create': typeof AuthenticatedBucketCreateRoute
}
export interface FileRoutesByTo {
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/bucket/$bucketId': typeof AuthenticatedBucketBucketIdRoute
  '/bucket/create': typeof AuthenticatedBucketCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bucket/$bucketId': typeof AuthenticatedBucketBucketIdRoute
  '/_authenticated/bucket/create': typeof AuthenticatedBucketCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/bucket/$bucketId'
    | '/bucket/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/callback'
    | '/auth/login'
    | '/'
    | '/bucket/$bucketId'
    | '/bucket/create'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth/callback'
    | '/auth/login'
    | '/_authenticated/'
    | '/_authenticated/bucket/$bucketId'
    | '/_authenticated/bucket/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bucket/create': {
      id: '/_authenticated/bucket/create'
      path: '/bucket/create'
      fullPath: '/bucket/create'
      preLoaderRoute: typeof AuthenticatedBucketCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bucket/$bucketId': {
      id: '/_authenticated/bucket/$bucketId'
      path: '/bucket/$bucketId'
      fullPath: '/bucket/$bucketId'
      preLoaderRoute: typeof AuthenticatedBucketBucketIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBucketBucketIdRoute: typeof AuthenticatedBucketBucketIdRoute
  AuthenticatedBucketCreateRoute: typeof AuthenticatedBucketCreateRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBucketBucketIdRoute: AuthenticatedBucketBucketIdRoute,
  AuthenticatedBucketCreateRoute: AuthenticatedBucketCreateRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
