/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BucketCreateRouteImport } from './routes/bucket/create'
import { Route as BucketBucketIdRouteImport } from './routes/bucket/$bucketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketCreateRoute = BucketCreateRouteImport.update({
  id: '/bucket/create',
  path: '/bucket/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketBucketIdRoute = BucketBucketIdRouteImport.update({
  id: '/bucket/$bucketId',
  path: '/bucket/$bucketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bucket/$bucketId': typeof BucketBucketIdRoute
  '/bucket/create': typeof BucketCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bucket/$bucketId': typeof BucketBucketIdRoute
  '/bucket/create': typeof BucketCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bucket/$bucketId': typeof BucketBucketIdRoute
  '/bucket/create': typeof BucketCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bucket/$bucketId' | '/bucket/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bucket/$bucketId' | '/bucket/create'
  id: '__root__' | '/' | '/bucket/$bucketId' | '/bucket/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BucketBucketIdRoute: typeof BucketBucketIdRoute
  BucketCreateRoute: typeof BucketCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bucket/create': {
      id: '/bucket/create'
      path: '/bucket/create'
      fullPath: '/bucket/create'
      preLoaderRoute: typeof BucketCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bucket/$bucketId': {
      id: '/bucket/$bucketId'
      path: '/bucket/$bucketId'
      fullPath: '/bucket/$bucketId'
      preLoaderRoute: typeof BucketBucketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BucketBucketIdRoute: BucketBucketIdRoute,
  BucketCreateRoute: BucketCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
